In [2]:
# MNIST handwritten digits classification with 2-layer MLP

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Load the data
data = pd.read_csv('train.csv')

In [11]:
print(data.shape)

(42000, 785)


In [ ]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

# Split the data into train and test sets
split = int(0.8*m) # 80% of the data is used for training
train_data = data[:split].T # Transpose the data
test_data = data[split:].T

# Split the train and test data into X and Y sets
train_X = train_data[:-1]/255 # Normalize the data
train_Y = train_data[-1]
test_X = test_data[:-1]/255
test_Y = test_data[-1]


In [12]:
a = np.random.randn(5, 2)
print(a)
a = a.T
print(a)
print(a[-1])

[[-0.70716398  0.58448827]
 [-0.61214649 -0.43555537]
 [-0.34874509  0.31157287]
 [ 1.28660164 -0.18705519]
 [-0.97152492  0.55564096]]
[[-0.70716398 -0.61214649 -0.34874509  1.28660164 -0.97152492]
 [ 0.58448827 -0.43555537  0.31157287 -0.18705519  0.55564096]]
[ 0.58448827 -0.43555537  0.31157287 -0.18705519  0.55564096]
